python training/train_node.py --world_size 1 --graph_type ER --partition_method metis
python training/train_node.py --world_size 2 --graph_type ER --partition_method metis
python training/train_node.py --world_size 3 --graph_type ER --partition_method metis
python training/train_node.py --world_size 1 --graph_type BA --partition_method metis
python training/train_node.py --world_size 2 --graph_type BA --partition_method metis
python training/train_node.py --world_size 3 --graph_type BA --partition_method metis
python training/train_node.py --world_size 1 --graph_type SBM --partition_method metis
python training/train_node.py --world_size 2 --graph_type SBM --partition_method metis
python training/train_node.py --world_size 3 --graph_type SBM --partition_method metis
python training/train_node.py --world_size 1 --graph_type ER --partition_method random
python training/train_node.py --world_size 2 --graph_type ER --partition_method random
python training/train_node.py --world_size 3 --graph_type ER --partition_method random
python training/train_node.py --world_size 1 --graph_type BA --partition_method random
python training/train_node.py --world_size 2 --graph_type BA --partition_method random
python training/train_node.py --world_size 3 --graph_type BA --partition_method random
python training/train_node.py --world_size 1 --graph_type SBM --partition_method random
python training/train_node.py --world_size 2 --graph_type SBM --partition_method random
python training/train_node.py --world_size 3 --graph_type SBM --partition_method random